import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LeftBar from "@/components/LeftBar";
import RightBar from "@/components/RightBar";
import Header from "@/components/Header";
import { ReactNode } from "react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

type DashboardLayoutProps = {
    children: ReactNode;
};

export default function DashboardLayout({ children }: DashboardLayoutProps) {
    return (
        <div className="flex flex-col h-full">
            {/* <Header /> */}

            <div className="flex flex-row h-screen">
                <div className="w-1/5 shadow-2xl shadow-slate-600 border-r-2 border-gray-600">
                    <LeftBar />
                </div>

                <div className="w-3/5 bg-gray-600">{children}</div>

                <div className="w-1/5 bg-gray-600 border-l-2 border-gray-800">
                    <RightBar />
                </div>
            </div>
        </div>
    );
}
